import "./globals.css";

import Authorize from "@/components/Authorize";
import Footer from "@/components/footer/Footer";
import { Golos_Text } from "next/font/google";
import Header from "@/components/header/Header";
import type { Metadata } from "next";
import { ToastContainer } from "react-toastify";

const golos = Golos_Text({
  variable: "--font-golos",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Flood Analytics",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${golos.variable} antialiased bg-background`}
      >

        <ToastContainer position="bottom-right" />

        <Authorize>
          <Header />

          <div className="relative min-h-[70dvh] grow flex flex-col pb-16">
            {children}
          </div>

          <Footer />
        </Authorize>
      </body>
    </html>
  );
}
