version: '3.8'

services:

  # PostgreSQL
  db-info:
    image: postgres:15
    container_name: db-1
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: nic
      POSTGRES_PASSWORD: Astana2024!bigdata
      POSTGRES_DB: flood-info
    volumes:
      - postgres_data_info:/var/lib/postgresql/data

  db-flood:
    image: postgres:15
    container_name: db-2
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: nic
      POSTGRES_PASSWORD: Astana2024!bigdata
      POSTGRES_DB: flood
    volumes:
      - postgres_data_flood:/var/lib/postgresql/data

  # NestJS backend
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - db-flood
    ports:
      - "3004:3004"
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/mydb

  # Next.js frontend
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - backend
    ports:
      - "3003:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3004

volumes:
  postgres_data_info:
  postgres_data_flood:
