import "./globals.css";

import { Golos_Text } from "next/font/google";
import type { Metadata } from "next";

const golos = Golos_Text({
  variable: "--font-golos",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Flood Analytics",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${golos.variable} antialiased bg-background`}
      >
        {children}
      </body>
    </html>
  );
}
